#!/usr/bin/env node
"use strict";

var _path = require("path");

var _path2 = _interopRequireDefault(_path);

var _fs = require("fs");

var _fs2 = _interopRequireDefault(_fs);

var _stream = require("stream");

var _index = require("../index");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/*
 * This file is part of CoreWorker.
 *
 * CoreWorker is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CoreWorker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CoreWorker.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright 2016 TeeAge-Beatz UG (haftungsbeschränkt)
 */

/*
 * Runs a Script that listens on stdin and logs it
 * This example will return a stream
 */
var dummyfile = _path2.default.join(__dirname, "Resources/dummyfile");
var writeStream = new _stream.Writable();
var grep = (0, _index.process)("grep first", "");
var stream = grep.stream();

writeStream.write = function (output) {
  console.log("> Found the following matches in file:\n", output.slice(0, -1));

  console.log("> Closing..");
  grep.kill();
};

_fs2.default.createReadStream(dummyfile).pipe(stream).pipe(writeStream);

//# sourceMappingURL=stream.js.map